language: python

python:
  - "3.7"
  - "3.8"

matrix:
  include:
  - python: 3.8
    dist: xenial

services:
  - postgresql

before_script:
  - psql -c 'create database test_graphene_djmoney;' -U postgres

before_install:
  - pip install poetry

install:
  - poetry install -v
  - pip install tox tox-travis

script:
  - tox

test:
  adapter: postgresql
  database: test_graphene_djmoney

# after_success:
#   - pip install coveralls
#   - coveralls

before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
deploy:
  provider: script
  script: poetry publish --build
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.8"

env:
  global:
    - secure: R5gy7puSZ4nGvgF0bEbhhc6PHjjALVMGGrICjmJpmCa8y/omQ1VWyDTzuAgbMvIDJQIqPFw8URnpjekZW5SytE7msCOu1VoW6pMezucVBXbg+2aXtLDH7Hr8LEjWfdEZYXw0oY3nnj3xN2Qg+1lhOfiCZ7Fxvl5tdkxboLzf8xAN1yXZuiNEE+DrmN700FaDFV8t4Vp7pxQVT7MvFSabmGXa6y5+Q3pEWeWFcaYTg4AQNsNwicwt4fmPVUxZFOlmyRsb7WoDUZyBKpETFLrupCNhFKlNrPus9meC3SGJB2Rp1lC+W8L7r4EzvlHdst8QV7JuQC6qFQUN74uUEowlJRXbG6WcBQmiEGVCLtqKxqjuakPr4Fj+gvQlDiWUEVDHKrRGfJ+xkjQ6e+jQ8U2mApbjNoAwMZZFCVn28Bt5sXqy3tymAN9+Ew15Kbws9FpThC+0IXbSNd2OfAoOiWTdsPzeCX60PvEZ51dOCPT/rBeWGIF1WMfdJ5BPytPCdKuTqEli6ET+qNdtaLEPFg+IEf2ARFSOx34WnZPQ0i/Q4L9Wrzs25BXw4ZLZE2y/97ubi6tMytW6mFXRKpu3FE21X0d34+br3/7hUKLcnSasolbVjNTiFcaJKsPAZvZzoTcH1pzwobEFbqZcHUNdRhxgKnwE6mxMCNKQ3gOBPfVYaps=
    - secure: DRb/pzHCoxw6U/J8NN5wpq40Px1yIkdH+Kdkse807XUvv0OcFTiSkXdeqGRkfNQZjmEHE/XOgfUKiUg2UdbVC2UgUAVSGHbCfrtcm83Omc6+Z6vIOoEWTXHliRV+5en/POhwxQzKb1X85cSsfPDURABpiWZX/PyoZKyX4mieThfvUKagHnAZth4t1k9oFq1VWcvBaCe8f4IAzoQFb4VP2TRoa4EksRFN55LDxKKQvs3/mJnqNbBxnZ3BU40x3PQb+ETXYts1kbTFOniH3v2AoClkm05xJIxrvXOxTvwFQuBFYxY2pM/AVydfXEPo9ksmBsMy3W3DJ7etUB+RyPqttLQz4nLIxKE6Bhv5ZgY9zQYFDzjzi4frlgSmnYsVzJ+cP4YHR+BRnjMwLdWdXZiUoASjtfJOCAkIuhFW9H22ZswkB4UWoK4sPBWLCoUw/nacjwgZBntmviQpWdHH/ffcBbNJpLO/ojhDSctCZzFDZOCFNXuMD9EmZUwLnPoPBifloRhTlneMBbtBHrYbSlNKUKMddVRp/tb2/sgoSj5YBIhGqfP424FoSRVjmTfs10TwReQn7JPtZNf+WOj5CrxYRvsXQuYJzl0zSt9/5ZRtvWqn4NJmNQ5OvBKFpKE4+26xY+CFOKIfxlTu5/6IcERkUxxLUYCAowiPj5nJm9Nq9cE=
